### ISSUE TITLE
No AUR package found for pitcom-ibhagwan

### ISSUE THREAD

**Issue by Clara-Haag** [ibhagwan/picom-ibhagwan-git#1]
As the title says _yay_ can't find this package, so i tried to check the links provided in the _README.md_ and saw they all lead to a 404 error page.
I'm quite new to linux and arch, so I don't know if you removed it from there and totally discontinued...
If that happened it would be quite sad, it seemed go be a good lib! :(

**Comment by Clara-Haag** [comment]
LOL JUST SAW MY MISTAKE
I'm so sorry 
Hope the best for your project :)

**Comment by flyingcakes85** [comment]
@Palitin Were you able to install this package via yay? It seems to have disappeared from AUR.
